# M7T14

La nostra empresa está colaborant amb el colectiu de metges per veure quina càrrega de treball están patint. La idea es veure quins metges han de donar suport a més pacients i quins sembla que tenen menys persones a càrrec.

Per fer-ho, ens han proporcionat un conjunt de dades (hospitals.csv) que conté informació detallada sobre els hospitals del país.

Crea una funció en Python que rebi com a paràmetres:

- Un DataFrame amb dades d’hospitals.
- El nombre n d’hospitals que es volen obtenir com a resultat.

La funció ha de calcular, per a cada hospital la càrrega de treball dels metges, utilitzant la següent fórmula: càrrega treball metge = num_llits /num_metges * percentatge ocupació

La funció ha de retornar els n hospitals amb més càrrega de treball per metge.

Executa la funció per obtenir 10 hospitals i després per obtenir-ne 20.

In [50]:
import pandas as pd

data = pd.read_csv("hospitales.csv", sep=";", encoding="latin-1")
number_of_hospitals_10 = 10
number_of_hospitals_20 = 20

# Una función que recibe los dos parámetros solicitados
def medical(data_frame, number):
    # se crea una columna adicional con el cálculo de la carga del personal médico. Formula de càrrega treball metge = num_llits /num_metges * percentatge ocupació
    data_frame["carga_de_trabajo"] = data_frame["num_camas"]/data_frame["num_medicos"]*data_frame["porcentaje_ocupacion"]
    # se agrupa la columna de carga de trabajo con el nombre de hospital para relacionar el cálculo con el nombre. 
    # se aplica función de máximo y ordena por carga de trabajo en orden descendente (sort_values(by=""".ascending=False)
    max_ocupy = data_frame.groupby("nombre")[["carga_de_trabajo"]].max().sort_values(by="carga_de_trabajo", ascending=False)
    # se retorna la función con el dato de la máxima ocupación y cortando al número que se haya introducido en la variable de number of hospitals
    return max_ocupy.head(number)

# para llamar a la función con 10 hospitales
medical(data, number_of_hospitals_10)
# para llamar a la función con 20 hospitales
medical(data, number_of_hospitals_20)

                                              carga_de_trabajo
nombre
Hospital de Sierrallana                            5677.200000
Hospital Doctor Jose Molina Orosa                  3279.400000
Hospital Universitario Virgen del Rocio            2612.384211
Hospital Universitario Puerta del Mar              2124.093750
Hospital de Tortosa Verge de la Cinta              1845.658333
Hospital Universitario Virgen Macarena             1641.280000
Hospital Mateu Orfila                              1577.352632
Hospital Infanta Margarita                         1262.866667
Hospital d'Olot i Comarcal de la Garrotxa          1101.660000
Hospital General Nuestra Señora del Prado           960.960000
Hospital San Pedro                                  811.476923
Complejo Asistencial de Zamora                      709.900794
Hospital de Jerez                                   699.841071
Hospital da Costa                                   607.265306
Hospital Universitario Marques de Valdecilla        581.752941
Hospital de Antequera                               574.386420
Hospital de Santa Marina                            539.613423
Hospital de Puerto Llano                            525.024706
Hospital de Zafra                                   518.077311
Hospital Universitario de Jaen                      486.015190

In [ ]:
import pandas as pd

data = pd.read_csv("hospitales.csv", sep=";", encoding="latin-1")
number_of_hospitals_10 = 10
number_of_hospitals_20 = 20

def medical(data_frame, number):
    data_frame["carga_de_trabajo"] = data_frame["num_camas"]/data_frame["num_medicos"]*data_frame["porcentaje_ocupacion"]
    max_ocupy = data_frame.groupby("nombre")[["carga_de_trabajo"]].max().sort_values(by="carga_de_trabajo", ascending=False)
    return max_ocupy.head(number)

medical(data, number_of_hospitals_10)
medical(data, number_of_hospitals_20)

                                              carga_de_trabajo
nombre
Hospital de Sierrallana                            5677.200000
Hospital Doctor Jose Molina Orosa                  3279.400000
Hospital Universitario Virgen del Rocio            2612.384211
Hospital Universitario Puerta del Mar              2124.093750
Hospital de Tortosa Verge de la Cinta              1845.658333
Hospital Universitario Virgen Macarena             1641.280000
Hospital Mateu Orfila                              1577.352632
Hospital Infanta Margarita                         1262.866667
Hospital d'Olot i Comarcal de la Garrotxa          1101.660000
Hospital General Nuestra Señora del Prado           960.960000
Hospital San Pedro                                  811.476923
Complejo Asistencial de Zamora                      709.900794
Hospital de Jerez                                   699.841071
Hospital da Costa                                   607.265306
Hospital Universitario Marques de Valdecilla        581.752941
Hospital de Antequera                               574.386420
Hospital de Santa Marina                            539.613423
Hospital de Puerto Llano                            525.024706
Hospital de Zafra                                   518.077311
Hospital Universitario de Jaen                      486.015190

In [12]:
data.head()

,hospital_id,nombre,localidad,provincia,comunidad_autonoma,presupuesto_anual_millones,num_camas,num_medicos,indice_satisfaccion,porcentaje_ocupacion,carga_de_trabajo
0,1,Hospital Universitario Torrecardenas,Almeria,Almeria,Andalucia,138.92,645,329,9.5,96.8,189.775076
1,2,Hospital de Poniente,Almeria,Almeria,Andalucia,150.52,575,228,4.2,78.5,197.971491
2,3,Hospital Universitario Puerta del Mar,Cadiz,Cadiz,Andalucia,496.80,834,32,6.4,81.5,2124.093750
3,4,Hospital de Jerez,Jerez de la Frontera,Cadiz,Andalucia,149.66,773,56,5.8,50.7,699.841071
4,5,Hospital Universitario Reina Sofia,Cordoba,Cordoba,Andalucia,358.41,277,433,1.9,61.4,39.278984