# Prácticas con pandas

### Minichuleta para trabajar con pandas

In [ ]:
import pandas as pd

df = pd.read_csv("Udemy_courses.csv")

# Exploración
df.shape
df.info()
df.dtypes
df.describe()

# Selección
df["columna"]
df[["col1", "col2"]]

# Filtros
df[df["col"] > 10]
df[(df["col1"] > 10) & (df["col2"] == "texto")]

# Agrupaciones
df.groupby("columna").size()
df.groupby("columna")["otra_columna"].mean()
df.groupby(["col1", "col2"])["col3"].mean()

# Nueva columna
df["nueva"] = df["col"] > 50000

# Cortar columnas
nuevo_df = df.iloc[:, :-6]

# ROUND 1 de ejercicios - Hospitales

### Ejercicio 1 — Filtros + ordenación

Dataset: hospitals

Obtén los 3 hospitales con más camas que cumplan:

- estén en Islas Canarias
- tengan más de 200 camas
- tengan indice_satisfaccion mayor a 8

In [ ]:
import pandas as pd

df_hospitales = pd.read_csv("hospitales.csv", sep=";", encoding="latin-1")

df_hospitales.head()

In [ ]:
df_filtrado_h = df_hospitales[(df_hospitales["num_camas"] > 200) & 
                              (df_hospitales["indice_satisfaccion"] > 8) & 
                              (df_hospitales["comunidad_autonoma"] == "Andalucia")]


df_filtrado_h.groupby("nombre").max("num_camas").sort_values(by = "num_camas", ascending=False).head(3)

### Ejercicio 2 — Filtro + agregación

Dataset: hospitals

Calcula la media de satisfacción de los hospitales que tienen más del 70% de ocupación, agrupado por:

- comunidad_autonoma
- Ordena el resultado de mayor a menor satisfacción.

In [ ]:
df_ocupacion = df_hospitales[df_hospitales["porcentaje_ocupacion"] > 70]
df_ocupacion.groupby("comunidad_autonoma").mean("indice_satisfaccion").sort_values(by = "indice_satisfaccion", ascending=False)

### Ejercicio 3 — Groupby doble

Dataset: hospitals

Para cada: comunidad_autonoma y provincia

Calcula:

- número de hospitales
- total de camas
- media de satisfacción

Ordena el resultado por total de camas (descendente).

In [ ]:
# COLOCANDO NOMBRE A LAS COLUMNAS
df_hospitales.groupby(["comunidad_autonoma", "provincia"]).agg(
    num_hospitales = ("hospital_id", "count"),
    total_camas = ("num_camas", "sum"),
    media_satisfaccion = ("indice_satisfaccion", "mean")
)

# SIN COLOCARLE NOMBRE A LAS COLUMNAS
# df_hospitales.groupby(["comunidad_autonoma", "provincia"]).agg({
#     "hospital_id": "count",
#     "num_camas": "sum",
#     "indice_satisfaccion": "mean"
# })

### Ejercicio 4 — Filtro de texto + conteo

Dataset: hospitals

Encuentra cuántos hospitales hay por comunidad autónoma cuyo:
- nombre contenga "Universitario"
- Ordena el resultado de mayor a menor.

In [ ]:
df_texto_conteo = df_hospitales[df_hospitales["nombre"].str.contains("Universitario")]
df_texto_conteo.groupby("comunidad_autonoma")["hospital_id"].count().sort_values(ascending=False) # No necesita el by porque ya no es un df sino una serie

# ROUND 2 de ejercicios - Udemy

### Ejercicio 1 — Ranking

Dataset: Udemy_courses

Obtén los 10 cursos con más subscribers que:
- sean paid (valores booleanos True o False)
- tengan rating mayor que 4.8

Muestra:
- course_title
- subject
- num_subscribers
- num_reviews
- Ordena por num_subscribers descendente.

In [46]:
import pandas as pd

df_udemy = pd.read_csv("udemy_courses.csv")

# df_udemy.head()
df_udemy_ex1 = df_udemy[(df_udemy["rating"] > 4.8) & (df_udemy["is_paid"] == True)]
df_udemy_ex1[["title", "category", "num_subscribers", "num_reviews"]].sort_values(by="num_subscribers", ascending=False).head(10)


# ENCADENADO
df_udemy_ex1[
    (df_udemy_ex1["rating"] > 4.8) & (df_udemy_ex1["is_paid"])
][["title", "category", "num_subscribers", "num_reviews"]] \
.sort_values(by="num_subscribers", ascending=False) \
.head(10)

,title,category,num_subscribers,num_reviews
745,R Programming For Absolute Beginners,Development,155812,3108
1171,"Learn How To Build Amazing Websites w/ HTML, C...",Development,103057,1839
111,Learn and Understand AngularJS,Development,100018,22073
683,Database Design,Development,93494,3439
214,Python 3: Deep Dive (Part 1 - Functional),Development,62749,11830
2637,Data Science Mastery with Python: Comprehensiv...,Development,54096,550
3101,Data Science Real-World Case Studies - Hands O...,Development,52591,425
189,The Modern JavaScript Bootcamp,Development,51344,13099
2424,Django 4 - Learn to Build EMS Web Application ...,Development,42668,639
3068,WordPress for Beginners,Development,39134,431

### Ejercicio 2 - condicionales if, def, .loc y lambda

Crea una nueva columna llamada popularitat con estas reglas:

num_subscribers > 50000 → "Alta"

10000 <= num_subscribers <= 50000 → "Mitjana"

num_subscribers < 10000 → "Baixa"

In [73]:
# Con .loc
df_udemy_ex2 = df_udemy.copy()
df_udemy_ex2["popularitat"] = ""

df_udemy_ex2.loc[df_udemy_ex2["num_subscribers"] > 50000, "popularitat"] = "Alta"
# df_udemy_ex2.loc[(df_udemy_ex2["num_subscribers"] >= 10000) & (df_udemy_ex2["num_subscribers"] <= 50000), "popularitat"] = "Mitjana"
df_udemy_ex2.loc[df_udemy_ex2["num_subscribers"].between(10000, 50000), "popularitat"] = "Mitjana"
df_udemy_ex2.loc[df_udemy_ex2["num_subscribers"] < 10000, "popularitat"] = "Baixa"

df_udemy_ex2.tail(10)

,id,title,url,is_paid,instructor_names,category,headline,num_subscribers,rating,num_reviews,instructional_level,objectives,curriculum,popularitat
3681,2445302,Django with GraphQL,https://www.udemy.com/course/django-with-graphql/,True,Krystian Czekalski,Development,Integrating GraphQL API with Django Framework,2056,3.506517,318,Beginner Level,Basics of Django Framework Basics of GraphQL H...,"Introduction, Introduction, Technology overvie...",Baixa
3682,3186142,Postman Testing for OAuth Authorization & Auth...,https://www.udemy.com/course/hands-on-oauth-au...,True,"Valentin Despa, Valentin Despa - Support",Development,Learn about why OAuth is important and how to ...,5575,4.309832,318,Intermediate Level,Learn the fundamentals or OAuth Use OAuth to a...,"Introduction, Introduction to APIs and Postman...",Baixa
3683,575880,The Complete Wordpress Course - Build Your Own...,https://www.udemy.com/course/wordpresscourse/,True,"Joe Parys, Justin Nifong, Joe Parys Support",Development,In this course students will learn a complete ...,25029,3.848326,318,All Levels,Learn how to use wordpress to create and build...,"Introduction, Welcome To Our Course! Learn How...",Mitjana
3684,1319568,Yii2 beginner to professional,https://www.udemy.com/course/yii2-beginner-to-...,True,Femi Ibiwoye,Development,Learn Yii2 framework from basic to advance lev...,1789,4.373073,318,All Levels,Build website with yii2 from scratch Understan...,"Getting started, Introduction, Install compose...",Baixa
3685,4866490,2024 R Programming Bootcamp for Absolute Begin...,https://www.udemy.com/course/2022-r-programmin...,True,Toppers Bootcamp,Development,R Programming course suitable for Absolute Beg...,43628,4.197298,318,Beginner Level,Basics of R Programming Data Structures in R C...,"Basics of R Programming, Instructor's Note, In...",Mitjana
3686,689522,Data Visualization with MATLAB - Projects and ...,https://www.udemy.com/course/data-visualizatio...,True,"Tod Vachev, Hristo Zhivomirov",Development,"Learn how to Visualize Data with MATLAB in 2D,...",3522,4.041048,318,Intermediate Level,Create 2D plots with MATLAB Create 3D plots wi...,"Introduction, Introduction, Basic Settings and...",Baixa
3687,5246736,Advanced WordPress & Elementor 2024 | Build Dy...,https://www.udemy.com/course/advanced-wordpres...,True,Ricky Wallace,Development,Build ANY website imaginable with WordPress &a...,2580,4.682569,317,Intermediate Level,Learn how to create visually stunning and full...,"Introduction, Introduction, Who is this course...",Baixa
3688,5018456,Web Design Course for Beginners to Intermediate,https://www.udemy.com/course/web-development-b...,True,Stephen Koel Soren,Development,"Learn the Basics of HTML, CSS, Wordpress and g...",27891,4.540056,317,Beginner Level,Tag Element Attributes Choosing Editor Visual ...,"Introduction, Introduction, Starting HTML, Nee...",Mitjana
3689,1676620,D3.js in Action: Build 17 D3.js Data Visualiza...,https://www.udemy.com/course/d3js-data-visuali...,True,Crypters Infotech,Development,D3.js (V 5) from Scratch! Build Useful D3.js D...,3325,4.438985,317,All Levels,Learn D3 from beginner to professional level D...,Be Familiar with D3.js (Introduction to D3.js)...,Baixa
3690,4100126,Salesforce Development Master Training for Beg...,https://www.udemy.com/course/salesforce-develo...,True,Shrey Sharma,Development,Learn Salesforce Development from scratch and ...,2360,4.105863,317,Beginner Level,Salesforce Development Salesforce Certificatio...,"Course Introduction, Introduction, APEX Basics...",Baixa

In [48]:
# Con .loc EXPLICACIÓN PASO A PASO

# todas las filas quedan con texto vacío.
df_udemy_ex2["popularitat"] = ""

df_udemy_ex2.loc[df_udemy_ex2["num_subscribers"] > 50000, "popularitat"] = "Alta"
# .loc sirve para seleccionar filas y columnas.
# Aquí estamos diciendo:
# en las filas donde "num_subscribers" sea mayor que 50000,
# en la columna "popularitat", escribe "Alta".

df_udemy_ex2.loc[(df_udemy_ex2["num_subscribers"] >= 10000) & (df_udemy_ex2["num_subscribers"] <= 50000),"popularitat"] = "Mitjana"
# Aquí seleccionamos las filas donde "num_subscribers" esté entre 10000 y 50000.
# Ojo:
# - >= 10000 significa "mayor o igual que 10000"
# - <= 50000 significa "menor o igual que 50000"
# - & significa "y", o sea, las dos condiciones deben cumplirse a la vez.
# En esas filas, en la columna "popularitat", se escribe "Mitjana".

df_udemy_ex2.loc[df_udemy_ex2["num_subscribers"] < 10000, "popularitat"] = "Baixa"
# Aquí seleccionamos las filas donde "num_subscribers" sea menor que 10000.
# En esas filas, en la columna "popularitat", se escribe "Baixa".

In [49]:
# Con def
def popularidad(x):
    if x > 50000:
        return "Alta"
    elif 10000 <= x <= 50000:
        return "Mitjana"
    else:
        return "Baixa"

df_udemy_ex2["popularitat"] = df_udemy_ex2["num_subscribers"].apply(popularidad)

df_udemy_ex2.head()

# Definimos una función llamada "popularidad"
# x representa cada valor individual de la columna num_subscribers
# Si el valor es mayor que 50000, devuelve "Alta"
# Si el valor está entre 10000 y 50000, devuelve "Mitjana"
# # Si no se cumple ninguna de las condiciones anteriores
# # significa que es menor que 10000, así que devuelve "Baixa"
# apply aplica la función "popularidad" a cada valor X de la columna "num_subscribers". Apply es quien elige a qué aplicarle la función
# El resultado de cada fila se guarda en la nueva columna "popularitat"

,id,title,url,is_paid,instructor_names,category,headline,num_subscribers,rating,num_reviews,instructional_level,objectives,curriculum,popularitat
0,567828,The Complete Python Bootcamp From Zero to Hero...,https://www.udemy.com/course/complete-python-b...,True,"Jose Portilla, Pierian Training",Development,Learn Python like a Professional Start from t...,1976866,4.576494,521219,All Levels,You will learn how to leverage the power of Py...,"Course Overview, Auto-Welcome Message, Course ...",Alta
1,1565838,The Complete 2024 Web Development Bootcamp,https://www.udemy.com/course/the-complete-web-...,True,"Dr. Angela Yu, Developer and Lead Instructor",Development,Become a Full-Stack Web Developer with just ON...,1362586,4.679065,409793,All Levels,Build 16 web development projects for your por...,"Front-End Web Development, What You'll Get in ...",Alta
2,2776760,100 Days of Code: The Complete Python Pro Boot...,https://www.udemy.com/course/100-days-of-code/,True,"Dr. Angela Yu, Developer and Lead Instructor",Development,Master Python by building 100 projects in 100 ...,1417942,4.698768,331803,All Levels,You will master the Python programming languag...,Day 1 - Beginner - Working with Variables in P...,Alta
3,625204,The Web Developer Bootcamp 2024,https://www.udemy.com/course/the-web-developer...,True,Colt Steele,Development,10 Hours of React just added. Become a Develop...,923815,4.673450,276723,All Levels,"The ins and outs of HTML5, CSS3, and Modern Ja...","Course Orientation, Welcome To The Course!, Jo...",Alta
4,1362070,React - The Complete Guide 2024 (incl. Next.js...,https://www.udemy.com/course/react-the-complet...,True,"Academind by Maximilian Schwarzmüller, Maximil...",Development,Dive in and learn React.js from scratch! Learn...,909848,4.638643,220051,All Levels,Learn React from the ground up and finish the ...,"Getting Started, Welcome To The Course!, What ...",Alta

In [51]:
df_udemy_ex2["popularitat"] = df_udemy_ex2["num_subscribers"].apply(
    lambda x: "Alta" if x > 50000
    else "Mitjana" if 10000 <= x <= 50000
    else "Baixa"
)

df_udemy_ex2.head()
# apply recorre cada valor de la columna "num_subscribers".
# lambda x crea una función pequeña donde x representa cada valor de la columna.
# Si x > 50000 devuelve "Alta".
# Si no, revisa la siguiente condición: si x está entre 10000 y 50000 devuelve "Mitjana".
# Si no se cumple ninguna de las anteriores, devuelve "Baixa".
# El resultado final se guarda en la nueva columna "popularitat".

,id,title,url,is_paid,instructor_names,category,headline,num_subscribers,rating,num_reviews,instructional_level,objectives,curriculum,popularitat
0,567828,The Complete Python Bootcamp From Zero to Hero...,https://www.udemy.com/course/complete-python-b...,True,"Jose Portilla, Pierian Training",Development,Learn Python like a Professional Start from t...,1976866,4.576494,521219,All Levels,You will learn how to leverage the power of Py...,"Course Overview, Auto-Welcome Message, Course ...",Alta
1,1565838,The Complete 2024 Web Development Bootcamp,https://www.udemy.com/course/the-complete-web-...,True,"Dr. Angela Yu, Developer and Lead Instructor",Development,Become a Full-Stack Web Developer with just ON...,1362586,4.679065,409793,All Levels,Build 16 web development projects for your por...,"Front-End Web Development, What You'll Get in ...",Alta
2,2776760,100 Days of Code: The Complete Python Pro Boot...,https://www.udemy.com/course/100-days-of-code/,True,"Dr. Angela Yu, Developer and Lead Instructor",Development,Master Python by building 100 projects in 100 ...,1417942,4.698768,331803,All Levels,You will master the Python programming languag...,Day 1 - Beginner - Working with Variables in P...,Alta
3,625204,The Web Developer Bootcamp 2024,https://www.udemy.com/course/the-web-developer...,True,Colt Steele,Development,10 Hours of React just added. Become a Develop...,923815,4.673450,276723,All Levels,"The ins and outs of HTML5, CSS3, and Modern Ja...","Course Orientation, Welcome To The Course!, Jo...",Alta
4,1362070,React - The Complete Guide 2024 (incl. Next.js...,https://www.udemy.com/course/react-the-complet...,True,"Academind by Maximilian Schwarzmüller, Maximil...",Development,Dive in and learn React.js from scratch! Learn...,909848,4.638643,220051,All Levels,Learn React from the ground up and finish the ...,"Getting Started, Welcome To The Course!, What ...",Alta

### Ejercicio 3 -  Añadir columna a partir de una columna booleana
Crea una nueva columna llamada course_type:

si is_paid == True → "Payment needed"

si is_paid == False → "Free"

In [ ]:
df_udemy_ex3 = df_udemy.copy()
df_udemy_ex3.head()

df_udemy_ex3["course_type"] = ""
# df_udemy_ex3.head() - para ver la columna vacía

df_udemy_ex3.loc[df_udemy_ex3["is_paid"] == True, "curs_type"] = "Payment needed"
df_udemy_ex3.loc[df_udemy_ex3["is_paid"] == False, "curs_type"] = "Free"

df_udemy_ex3.head()

,id,title,url,is_paid,instructor_names,category,headline,num_subscribers,rating,num_reviews,instructional_level,objectives,curriculum,curs_type
0,567828,The Complete Python Bootcamp From Zero to Hero...,https://www.udemy.com/course/complete-python-b...,True,"Jose Portilla, Pierian Training",Development,Learn Python like a Professional Start from t...,1976866,4.576494,521219,All Levels,You will learn how to leverage the power of Py...,"Course Overview, Auto-Welcome Message, Course ...",Payment needed
1,1565838,The Complete 2024 Web Development Bootcamp,https://www.udemy.com/course/the-complete-web-...,True,"Dr. Angela Yu, Developer and Lead Instructor",Development,Become a Full-Stack Web Developer with just ON...,1362586,4.679065,409793,All Levels,Build 16 web development projects for your por...,"Front-End Web Development, What You'll Get in ...",Payment needed
2,2776760,100 Days of Code: The Complete Python Pro Boot...,https://www.udemy.com/course/100-days-of-code/,True,"Dr. Angela Yu, Developer and Lead Instructor",Development,Master Python by building 100 projects in 100 ...,1417942,4.698768,331803,All Levels,You will master the Python programming languag...,Day 1 - Beginner - Working with Variables in P...,Payment needed
3,625204,The Web Developer Bootcamp 2024,https://www.udemy.com/course/the-web-developer...,True,Colt Steele,Development,10 Hours of React just added. Become a Develop...,923815,4.673450,276723,All Levels,"The ins and outs of HTML5, CSS3, and Modern Ja...","Course Orientation, Welcome To The Course!, Jo...",Payment needed
4,1362070,React - The Complete Guide 2024 (incl. Next.js...,https://www.udemy.com/course/react-the-complet...,True,"Academind by Maximilian Schwarzmüller, Maximil...",Development,Dive in and learn React.js from scratch! Learn...,909848,4.638643,220051,All Levels,Learn React from the ground up and finish the ...,"Getting Started, Welcome To The Course!, What ...",Payment needed

### Ejercicio 4 - Operación math con Round

Crea una nueva columna llamada ratio_reviews que sea:

num_reviews / num_subscribers

Luego redondea el resultado a 2 decimales.

In [ ]:
df_udemy_ex4 = df_udemy.copy()
df_udemy_ex4["ratio_reviews"] = (df_udemy_ex4["num_reviews"]/df_udemy_ex4["num_subscribers"]).round(2)
df_udemy_ex4.head()

,id,title,url,is_paid,instructor_names,category,headline,num_subscribers,rating,num_reviews,instructional_level,objectives,curriculum,ratio_reviews
0,567828,The Complete Python Bootcamp From Zero to Hero...,https://www.udemy.com/course/complete-python-b...,True,"Jose Portilla, Pierian Training",Development,Learn Python like a Professional Start from t...,1976866,4.576494,521219,All Levels,You will learn how to leverage the power of Py...,"Course Overview, Auto-Welcome Message, Course ...",0.26
1,1565838,The Complete 2024 Web Development Bootcamp,https://www.udemy.com/course/the-complete-web-...,True,"Dr. Angela Yu, Developer and Lead Instructor",Development,Become a Full-Stack Web Developer with just ON...,1362586,4.679065,409793,All Levels,Build 16 web development projects for your por...,"Front-End Web Development, What You'll Get in ...",0.30
2,2776760,100 Days of Code: The Complete Python Pro Boot...,https://www.udemy.com/course/100-days-of-code/,True,"Dr. Angela Yu, Developer and Lead Instructor",Development,Master Python by building 100 projects in 100 ...,1417942,4.698768,331803,All Levels,You will master the Python programming languag...,Day 1 - Beginner - Working with Variables in P...,0.23
3,625204,The Web Developer Bootcamp 2024,https://www.udemy.com/course/the-web-developer...,True,Colt Steele,Development,10 Hours of React just added. Become a Develop...,923815,4.673450,276723,All Levels,"The ins and outs of HTML5, CSS3, and Modern Ja...","Course Orientation, Welcome To The Course!, Jo...",0.30
4,1362070,React - The Complete Guide 2024 (incl. Next.js...,https://www.udemy.com/course/react-the-complet...,True,"Academind by Maximilian Schwarzmüller, Maximil...",Development,Dive in and learn React.js from scratch! Learn...,909848,4.638643,220051,All Levels,Learn React from the ground up and finish the ...,"Getting Started, Welcome To The Course!, What ...",0.24

### Ejercicio 5 - condicionales y más

Crea una nueva columna llamada len_title que indique:

"Sí" si el título tiene más de 40 caracteres

"No" en caso contrario

Pista: usar .str.len().

In [75]:
df_udemy_ex5 = df_udemy.copy()
df_udemy_ex5["len_title"] = ""

df_udemy_ex5.loc[df_udemy_ex5["title"].str.len() > 40, "len_title"] = "Sí"
df_udemy_ex5.loc[df_udemy_ex5["title"].str.len() <= 40, "len_title"] = "No"

df_udemy_ex5.head()

,id,title,url,is_paid,instructor_names,category,headline,num_subscribers,rating,num_reviews,instructional_level,objectives,curriculum,len_title
0,567828,The Complete Python Bootcamp From Zero to Hero...,https://www.udemy.com/course/complete-python-b...,True,"Jose Portilla, Pierian Training",Development,Learn Python like a Professional Start from t...,1976866,4.576494,521219,All Levels,You will learn how to leverage the power of Py...,"Course Overview, Auto-Welcome Message, Course ...",Sí
1,1565838,The Complete 2024 Web Development Bootcamp,https://www.udemy.com/course/the-complete-web-...,True,"Dr. Angela Yu, Developer and Lead Instructor",Development,Become a Full-Stack Web Developer with just ON...,1362586,4.679065,409793,All Levels,Build 16 web development projects for your por...,"Front-End Web Development, What You'll Get in ...",Sí
2,2776760,100 Days of Code: The Complete Python Pro Boot...,https://www.udemy.com/course/100-days-of-code/,True,"Dr. Angela Yu, Developer and Lead Instructor",Development,Master Python by building 100 projects in 100 ...,1417942,4.698768,331803,All Levels,You will master the Python programming languag...,Day 1 - Beginner - Working with Variables in P...,Sí
3,625204,The Web Developer Bootcamp 2024,https://www.udemy.com/course/the-web-developer...,True,Colt Steele,Development,10 Hours of React just added. Become a Develop...,923815,4.673450,276723,All Levels,"The ins and outs of HTML5, CSS3, and Modern Ja...","Course Orientation, Welcome To The Course!, Jo...",No
4,1362070,React - The Complete Guide 2024 (incl. Next.js...,https://www.udemy.com/course/react-the-complet...,True,"Academind by Maximilian Schwarzmüller, Maximil...",Development,Dive in and learn React.js from scratch! Learn...,909848,4.638643,220051,All Levels,Learn React from the ground up and finish the ...,"Getting Started, Welcome To The Course!, What ...",Sí

### Ejercicio 6 - Eliminar columnas

Elimina las columnas: url, headline, curriculum, objectives

Guarda el resultado en un nuevo DataFrame llamado df_reduced

In [ ]:
df_udemy_reduced = df_udemy.copy()
df_udemy_reduced = df_udemy_reduced.drop(["url", "curriculum", "headline", "objectives"], axis=1)

df_udemy_reduced.head()

,id,title,is_paid,instructor_names,category,num_subscribers,rating,num_reviews,instructional_level
0,567828,The Complete Python Bootcamp From Zero to Hero...,True,"Jose Portilla, Pierian Training",Development,1976866,4.576494,521219,All Levels
1,1565838,The Complete 2024 Web Development Bootcamp,True,"Dr. Angela Yu, Developer and Lead Instructor",Development,1362586,4.679065,409793,All Levels
2,2776760,100 Days of Code: The Complete Python Pro Boot...,True,"Dr. Angela Yu, Developer and Lead Instructor",Development,1417942,4.698768,331803,All Levels
3,625204,The Web Developer Bootcamp 2024,True,Colt Steele,Development,923815,4.673450,276723,All Levels
4,1362070,React - The Complete Guide 2024 (incl. Next.js...,True,"Academind by Maximilian Schwarzmüller, Maximil...",Development,909848,4.638643,220051,All Levels

# ROUND 3 - crear def que reciban un DF

### Ejercicio 1 - retorna un df reducido con más de 500000 de suscriptores
Crea una función llamada cursos_populares(df) que reciba un DataFrame y filtre los cursos con más de 500000 suscriptores. 
- Además, debe mostrar solo title, category y num_subscribers
- ordene el resultado de mayor a menor por num_subscribers
- lo retorne

In [1]:
import pandas as pd

df_udemy = pd.read_csv("udemy_courses.csv")

def cursos_populares(df):
    df_filtrado_udemy = df[df["num_subscribers"] > 500000]
    df_last_filter = df_filtrado_udemy[["title", "category", "num_subscribers"]].sort_values(by="num_subscribers", ascending=False)
    return df_last_filter
cursos_populares(df_udemy)


# FILTRADO DE MUESTRA EN RETURN
# def cursos_populares(df):
#     df_filtrado_udemy = df[df["num_subscribers"] > 500000]
#     return df_filtrado_udemy[["title", "category", "num_subscribers"]].sort_values(by="num_subscribers", ascending=False)
# cursos_populares(df_udemy)

# MENOS LEGIBLE
# def cursos_populares(df):
#     df_filtrado_udemy = df[df["num_subscribers"] > 500000][["title", "category", "num_subscribers"]].sort_values(by="num_subscribers", ascending=False)
#     return df_filtrado_udemy
# cursos_populares(df_udemy)

,title,category,num_subscribers
0,The Complete Python Bootcamp From Zero to Hero...,Development,1976866
2,100 Days of Code: The Complete Python Pro Boot...,Development,1417942
1,The Complete 2024 Web Development Bootcamp,Development,1362586
12,Automate the Boring Stuff with Python Programming,Development,1134900
8,"Machine Learning A-Z: AI, Python & R + ChatGPT...",Development,1093550
5,The Complete JavaScript Course 2024: From Zero...,Development,948984
3,The Web Developer Bootcamp 2024,Development,923815
4,React - The Complete Guide 2024 (incl. Next.js...,Development,909848
7,Java 17 Masterclass: Start Coding in 2024,Development,884140
6,Angular - The Complete Guide (2024 Edition),Development,788455
9,Python for Data Science and Machine Learning B...,Development,737929
10,The Data Science Course: Complete Data Science...,Development,719783
101,The Complete Python Programming Course: Beginn...,Development,577417
157,Java Programming for Complete Beginners,Development,539194

### Ejercicio 2 - retorna un diccionario por subgrupos (.get_group())

Crea una función llamada course_level que reciba un DataFrame y un instructional_level y filtre solo ese nivel. Calcule:
- cantidad de cursos
- media de rating
- total de suscriptores
- retorne esos resultados

In [ ]:
df_udemy = pd.read_csv("udemy_courses.csv")

level_1 = "Beginner Level"
level_2 = "Intermediate Level"
level_3 = "Expert Level"

# SOLUCIÓN CON .get_group()
def course_level(df, level):

    df_level = df.groupby("instructional_level").get_group(level)

    total_number = df_level["id"].count()
    avg_course = df_level["rating"].mean()
    total_subscribers = df_level["num_subscribers"].sum()

    return (
        f"El total de cursos en este nivel es de: {total_number} cursos",
        f"El promedio de rating para este nivel es: {avg_course}",
        f"El total de suscriptores para este nivel es de: {total_subscribers}"
    )

course_level(df_udemy, level_3)


# SOLUCIÓN CON .get_group() y agg({})
def course_level(df, level):
    result = df.groupby("instructional_level").get_group(level).agg({
        "id": "count",
        "rating": "mean",
        "num_subscribers": "sum"
    })
    return (
        f"El total de cursos en este nivel es de: {int(result['id'])} cursos", # Le puse int porque el resultado me salía como float y realmente es un número entero
        f"El promedio de rating para este nivel es: {result['rating']}",
        f"El total de suscriptores para este nivel es de: {int(result['num_subscribers'])}"
    )
course_level(df_udemy, level_3)
# df_udemy.head()


# resumen = df.groupby('categoria').agg(
#     total_ventas=('ventas', 'sum'),
#     numero_registros=('ventas', 'count')

# )

('El total de cursos en este nivel es de: 46 cursos',
 'El promedio de rating para este nivel es: 4.332760228260869',
 'El total de suscriptores para este nivel es de: 794702')

### Ejercicio 3 - retorna df con nlargest

Crea una función que reciba un DataFrame y un número n

devuelva los n cursos con más num_subscribers mostrando solo: title, num_subscribers, rating

In [ ]:
import pandas as pd

df_udemy = pd.read_csv("udemy_courses.csv")
# number = 3
number = int(input("Escribe un número entero: "))


def top_courses_subscribers(df, nnumber):
    df_filtrado = df[["title", "num_subscribers", "rating"]]
    return df_filtrado.nlargest(nnumber, "num_subscribers")
    # return df_filtrado.sort_values(by="num_subscribers", ascending=False).head(nnumber)
top_courses_subscribers(df_udemy, number)


# df_udemy.head()

,title,num_subscribers,rating
0,The Complete Python Bootcamp From Zero to Hero...,1976866,4.576494
2,100 Days of Code: The Complete Python Pro Boot...,1417942,4.698768
1,The Complete 2024 Web Development Bootcamp,1362586,4.679065
12,Automate the Boring Stuff with Python Programming,1134900,4.626117
8,"Machine Learning A-Z: AI, Python & R + ChatGPT...",1093550,4.531372

### Ejercicio 4 - retorna con filtrado por condicionales

Crea una función que reciba un DataFrame y un número que representará el límite de popularidad que el usuario considera alto

La función debe:
- Crear una nueva columna llamada popularity_type.
- Clasificar los cursos según el número de suscriptores (num_subscribers) usando el límite recibido en la función.

Por ejemplo, si el límite es 50 000:

num_subscribers > limit → "Very popular"

10000 <= num_subscribers <= limit → "Moderately popular"

num_subscribers < 10000 → "Low popularity"

In [ ]:
# CON .LOC
df_udemy = pd.read_csv("udemy_courses.csv")
user_limit_popularity = 50000

def price_limit(df, limit):

    df_popularity = df.copy()
    df_popularity["popularity"] = ""
    df_popularity.loc[df_popularity["num_subscribers"] > limit, "popularity"] = "Very popular"
    df_popularity.loc[(df_popularity["num_subscribers"] >= 10000) & (df_popularity["num_subscribers"] <= limit), "popularity"] = "Moderately popular"
    df_popularity.loc[df_popularity["num_subscribers"] < 10000, "popularity"] = "Low popularity"

    return df_popularity

price_limit(df_udemy, user_limit_popularity)

,id,title,url,is_paid,instructor_names,category,headline,num_subscribers,rating,num_reviews,instructional_level,objectives,curriculum,popularity
0,567828,The Complete Python Bootcamp From Zero to Hero...,https://www.udemy.com/course/complete-python-b...,True,"Jose Portilla, Pierian Training",Development,Learn Python like a Professional Start from t...,1976866,4.576494,521219,All Levels,You will learn how to leverage the power of Py...,"Course Overview, Auto-Welcome Message, Course ...",Very popular
1,1565838,The Complete 2024 Web Development Bootcamp,https://www.udemy.com/course/the-complete-web-...,True,"Dr. Angela Yu, Developer and Lead Instructor",Development,Become a Full-Stack Web Developer with just ON...,1362586,4.679065,409793,All Levels,Build 16 web development projects for your por...,"Front-End Web Development, What You'll Get in ...",Very popular
2,2776760,100 Days of Code: The Complete Python Pro Boot...,https://www.udemy.com/course/100-days-of-code/,True,"Dr. Angela Yu, Developer and Lead Instructor",Development,Master Python by building 100 projects in 100 ...,1417942,4.698768,331803,All Levels,You will master the Python programming languag...,Day 1 - Beginner - Working with Variables in P...,Very popular
3,625204,The Web Developer Bootcamp 2024,https://www.udemy.com/course/the-web-developer...,True,Colt Steele,Development,10 Hours of React just added. Become a Develop...,923815,4.673450,276723,All Levels,"The ins and outs of HTML5, CSS3, and Modern Ja...","Course Orientation, Welcome To The Course!, Jo...",Very popular
4,1362070,React - The Complete Guide 2024 (incl. Next.js...,https://www.udemy.com/course/react-the-complet...,True,"Academind by Maximilian Schwarzmüller, Maximil...",Development,Dive in and learn React.js from scratch! Learn...,909848,4.638643,220051,All Levels,Learn React from the ground up and finish the ...,"Getting Started, Welcome To The Course!, What ...",Very popular
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3686,689522,Data Visualization with MATLAB - Projects and ...,https://www.udemy.com/course/data-visualizatio...,True,"Tod Vachev, Hristo Zhivomirov",Development,"Learn how to Visualize Data with MATLAB in 2D,...",3522,4.041048,318,Intermediate Level,Create 2D plots with MATLAB Create 3D plots wi...,"Introduction, Introduction, Basic Settings and...",Low popularity
3687,5246736,Advanced WordPress & Elementor 2024 | Build Dy...,https://www.udemy.com/course/advanced-wordpres...,True,Ricky Wallace,Development,Build ANY website imaginable with WordPress &a...,2580,4.682569,317,Intermediate Level,Learn how to create visually stunning and full...,"Introduction, Introduction, Who is this course...",Low popularity
3688,5018456,Web Design Course for Beginners to Intermediate,https://www.udemy.com/course/web-development-b...,True,Stephen Koel Soren,Development,"Learn the Basics of HTML, CSS, Wordpress and g...",27891,4.540056,317,Beginner Level,Tag Element Attributes Choosing Editor Visual ...,"Introduction, Introduction, Starting HTML, Nee...",Moderately popular
3689,1676620,D3.js in Action: Build 17 D3.js Data Visualiza...,https://www.udemy.com/course/d3js-data-visuali...,True,Crypters Infotech,Development,D3.js (V 5) from Scratch! Build Useful D3.js D...,3325,4.438985,317,All Levels,Learn D3 from beginner to professional level D...,Be Familiar with D3.js (Introduction to D3.js)...,Low popularity
3690,4100126,Salesforce Development Master Training for Beg...,https://www.udemy.com/course/salesforce-develo...,True,Shrey Sharma,Development,Learn Salesforce Development from scratch and ...,2360,4.105863,317,Beginner Level,Salesforce Development Salesforce Certificatio...,"Course Introduction, Introduction, APEX Basics...",Low popularity

In [108]:
# CON DOBLE DEF
df_udemy = pd.read_csv("udemy_courses.csv")
user_limit_popularity = 50000

def price_limit(df, limit):    

    df_popularity = df.copy()
    
    def popularity(x):
        if x > limit:
            return "Very popular"
        elif 10000 <= x <= limit:
            return "Moderately popular"
        else:
            return "Low popularity"
    
    df_popularity["Popularity"] = df_popularity["num_subscribers"].apply(popularity)
    return df_popularity

price_limit(df_udemy, user_limit_popularity)

,id,title,url,is_paid,instructor_names,category,headline,num_subscribers,rating,num_reviews,instructional_level,objectives,curriculum,Popularity
0,567828,The Complete Python Bootcamp From Zero to Hero...,https://www.udemy.com/course/complete-python-b...,True,"Jose Portilla, Pierian Training",Development,Learn Python like a Professional Start from t...,1976866,4.576494,521219,All Levels,You will learn how to leverage the power of Py...,"Course Overview, Auto-Welcome Message, Course ...",Very popular
1,1565838,The Complete 2024 Web Development Bootcamp,https://www.udemy.com/course/the-complete-web-...,True,"Dr. Angela Yu, Developer and Lead Instructor",Development,Become a Full-Stack Web Developer with just ON...,1362586,4.679065,409793,All Levels,Build 16 web development projects for your por...,"Front-End Web Development, What You'll Get in ...",Very popular
2,2776760,100 Days of Code: The Complete Python Pro Boot...,https://www.udemy.com/course/100-days-of-code/,True,"Dr. Angela Yu, Developer and Lead Instructor",Development,Master Python by building 100 projects in 100 ...,1417942,4.698768,331803,All Levels,You will master the Python programming languag...,Day 1 - Beginner - Working with Variables in P...,Very popular
3,625204,The Web Developer Bootcamp 2024,https://www.udemy.com/course/the-web-developer...,True,Colt Steele,Development,10 Hours of React just added. Become a Develop...,923815,4.673450,276723,All Levels,"The ins and outs of HTML5, CSS3, and Modern Ja...","Course Orientation, Welcome To The Course!, Jo...",Very popular
4,1362070,React - The Complete Guide 2024 (incl. Next.js...,https://www.udemy.com/course/react-the-complet...,True,"Academind by Maximilian Schwarzmüller, Maximil...",Development,Dive in and learn React.js from scratch! Learn...,909848,4.638643,220051,All Levels,Learn React from the ground up and finish the ...,"Getting Started, Welcome To The Course!, What ...",Very popular
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3686,689522,Data Visualization with MATLAB - Projects and ...,https://www.udemy.com/course/data-visualizatio...,True,"Tod Vachev, Hristo Zhivomirov",Development,"Learn how to Visualize Data with MATLAB in 2D,...",3522,4.041048,318,Intermediate Level,Create 2D plots with MATLAB Create 3D plots wi...,"Introduction, Introduction, Basic Settings and...",Low popularity
3687,5246736,Advanced WordPress & Elementor 2024 | Build Dy...,https://www.udemy.com/course/advanced-wordpres...,True,Ricky Wallace,Development,Build ANY website imaginable with WordPress &a...,2580,4.682569,317,Intermediate Level,Learn how to create visually stunning and full...,"Introduction, Introduction, Who is this course...",Low popularity
3688,5018456,Web Design Course for Beginners to Intermediate,https://www.udemy.com/course/web-development-b...,True,Stephen Koel Soren,Development,"Learn the Basics of HTML, CSS, Wordpress and g...",27891,4.540056,317,Beginner Level,Tag Element Attributes Choosing Editor Visual ...,"Introduction, Introduction, Starting HTML, Nee...",Moderately popular
3689,1676620,D3.js in Action: Build 17 D3.js Data Visualiza...,https://www.udemy.com/course/d3js-data-visuali...,True,Crypters Infotech,Development,D3.js (V 5) from Scratch! Build Useful D3.js D...,3325,4.438985,317,All Levels,Learn D3 from beginner to professional level D...,Be Familiar with D3.js (Introduction to D3.js)...,Low popularity
3690,4100126,Salesforce Development Master Training for Beg...,https://www.udemy.com/course/salesforce-develo...,True,Shrey Sharma,Development,Learn Salesforce Development from scratch and ...,2360,4.105863,317,Beginner Level,Salesforce Development Salesforce Certificatio...,"Course Introduction, Introduction, APEX Basics...",Low popularity

### Ejercicio 5
Crea una función llamada cursos_destacats(df, nivel) que reciba: un DataFrame y un nivel de curso, por ejemplo "Beginner Level"

La función debe:

- filtrar solo los cursos de ese nivel
- crear una nueva columna llamada recomended: "Yes" si rating >= 4.5 y num_reviews >= 1000, "No" en caso contrario
- retornar un DataFrame con estas columnas:title, instructional_level, num_subscribers, rating, num_reviews, Recomended
- ordenar el resultado de mayor a menor por num_subscribers

In [3]:
import pandas as pd
df_udemy = pd.read_csv("udemy_courses.csv")
nivel_1 = "Beginner Level"
nivel_2 = "Intermediate Level"
nivel_3 = "Expert Level"

def cursos_destacados(df, nivel):
    # df_filtrado = df.copy()
    # df_filtrado = df_filtrado[df_filtrado["instructional_level"] == nivel].copy()
    df_filtrado = df[df["instructional_level"] == nivel].copy() # Mejor copiar solo el filtrado, que es sobre el cual voy a trabajar
    df_filtrado["recomended"] = "No"
    df_filtrado.loc[(df_filtrado["rating"] >= 4.5) & (df_filtrado["num_reviews"] >= 1000), "recomended"] = "Yes"
    return df_filtrado[["title", "instructional_level", "num_subscribers", "rating", "num_reviews", "recomended"]].sort_values(by="num_subscribers", ascending=False)

cursos_destacados(df_udemy, nivel_2)

# Para revisar filtro
# cursos_destacados(df_udemy, nivel_2)["recomended"].value_counts
# cursos_destacados(df_udemy, nivel_2).info()

,title,instructional_level,num_subscribers,rating,num_reviews,recomended
1574,Learn Machine learning & AI [Beginner to advan...,Intermediate Level,270974,3.455324,1218,No
825,Modern JavaScript for React JS - ES6,Intermediate Level,238572,4.237619,2780,No
738,Python for beginners - Learn all the basics of...,Intermediate Level,216595,4.383688,3141,No
48,"Advanced CSS and Sass: Flexbox, Grid, Animatio...",Intermediate Level,214454,4.731044,44667,Yes
1728,Python Programming Beyond The Basics & Interme...,Intermediate Level,184929,4.636696,1062,Yes
...,...,...,...,...,...,...
3067,The Philosophy of FileMaker - Part 1,Intermediate Level,1336,4.902145,431,No
3466,Building reports in Java with JasperReports an...,Intermediate Level,1244,3.854279,351,No
3664,Introducing Microsoft Team Foundation Server 2017,Intermediate Level,1215,3.597324,320,No
3465,Customizing AppGini web applications,Intermediate Level,1127,4.599719,351,No
3372,Complete Guide to Creating COCO Datasets,Intermediate Level,954,4.605455,366,No

In [ ]:
def cursos_destacados(df, nivel):

    df_filtrado = df[df["instructional_level"] == nivel].copy()

    df_filtrado["recomended"] = "No"

    df_filtrado.loc[
        (df_filtrado["rating"] >= 4.5) & (df_filtrado["num_reviews"] >= 1000),
        "recomended"] = "Yes"

    return df_filtrado[["title","instructional_level","num_subscribers","rating","num_reviews","recomended"]].sort_values(by="num_subscribers", ascending=False)

### Ejercicio 6 - función que recibe df y número, crea columna calculada y retorna top nlargest

Crea una función llamada top_cursos(df, n) que reciba: un DataFrame y un número

La función debe:
- crear una nueva columna llamada index_rendiment con esta fórmula: (num_subscribers * rating) / num_reviews
- crear una nueva columna llamada TipusCurs: ""Premium" si rating >= 4.5 y num_subscribers >= 50000, "Standard" si rating >= 4.0 y rating < 4.5 y num_subscribers >= 10000, "Basic" en cualquier otro caso
- Ordenar el DataFrame de mayor a menor por index_rendiment	
- Retornar solo los n primeros cursos mostrando: title, rating, num_reviews, num_subscribers, TipusCurs

In [28]:
df_udemy = pd.read_csv("udemy_courses.csv")
number = 10

def top_cursos(df, n):
    df_copy = df.copy()

    df_copy["index_rendiment"] = df_copy["num_subscribers"] * df_copy["rating"] / df_copy["num_reviews"]

    df_copy["TipusCurs"] = "Basic"
    
    df_copy.loc[(df_copy["rating"] >= 4.5) & (df_copy["num_subscribers"] >= 50000), "TipusCurs"] = "Premium"
    df_copy.loc[(df_copy["rating"] >= 4.0) & (df_copy["rating"] < 4.5) & (df_copy["num_subscribers"] >= 10000), "TipusCurs"] = "Standard"

    return df_copy[["title","rating","num_reviews","num_subscribers","TipusCurs","index_rendiment"]].nlargest(n, "index_rendiment")
top_cursos(df_udemy, number)

,title,rating,num_reviews,num_subscribers,TipusCurs,index_rendiment
3370,Build Android Widgets from scratch (Learn 8 Wi...,4.573974,367,130573,Premium,1627.350049
3357,Gatsby JS | Build a personal blog using gatsbyJS,4.352398,369,110350,Standard,1301.591229
3203,Start Coding Browser Extensions Using JavaScript!,4.350950,400,116513,Standard,1267.355652
3059,Complete Progressive Web App Bootcamp,4.232895,433,128483,Standard,1256.016278
2722,Setup a Virtual Web Server using Linode or Dig...,4.314991,519,145760,Standard,1211.855802
2671,Intermediate Python Immersive Training | Boost...,3.955027,536,158265,Basic,1167.802977
3249,Learn XML-AJAX - For Beginners,4.434604,389,101849,Standard,1161.079647
2579,Applied Python: Building Projects with Python ...,4.387290,567,129771,Standard,1004.132294
2688,Advanced Foundations of Python Programming,4.114589,531,126216,Standard,978.016812
3259,Logistic Regression in R Studio,3.805112,387,98663,Basic,970.087249

### Ejercicio 7 - isin() .loc
Crea una función llamada hospitales_zona(df) que reciba un DataFrame y haga lo siguiente:

- cree una nueva columna llamada zona
- ponga "Sud" si comunidad_autonoma es "Andalucia", "Murcia" o "Extremadura"
- ponga "Nord-est" si comunidad_autonoma es "Cataluña" o "Aragón"
- ponga "Altres" en cualquier otro caso
- retorne solo estas columnas: hospital_id, comunidad_autonoma, num_camas, porcentaje_ocupacion, zona

In [ ]:
import pandas as pd

data = pd.read_csv("hospitales.csv", sep=";", encoding="latin-1")

def hospitales_zona(df):
    df_copy = df.copy()  # hacemos una copia para no modificar el df original

    df_copy["zona"] = "Altres"  # primero, todas las filas tendrán por defecto el valor "Altres"

    df_copy.loc[df_copy["comunidad_autonoma"].isin(["Andalucia", "Murcia", "Extremadura"]),"zona"] = "Sud"
    # si la comunidad está en esa lista, la columna "zona" pasa a valer "Sud"
    # df_copy.loc[(df_copy["comunidad_autonoma"] == "Andalucia") | # con OR
    # (df_copy["comunidad_autonoma"] == "Murcia") |
    # (df_copy["comunidad_autonoma"] == "Extremadura"),
    # "zona"] = "Sud"

    df_copy.loc[df_copy["comunidad_autonoma"].isin(["Cataluña", "Aragón"]),"zona"] = "Nord-est"
    # si la comunidad está en esta otra lista, "zona" pasa a valer "Nord-est"

    return df_copy[["hospital_id", "comunidad_autonoma", "num_camas", "porcentaje_ocupacion", "zona"]]
    # devolvemos solo las columnas que nos interesan

hospitales_zona(data)

     hospital_id comunidad_autonoma  num_camas  porcentaje_ocupacion    zona
0              1          Andalucia        645                  96.8     Sud
1              2          Andalucia        575                  78.5     Sud
2              3          Andalucia        834                  81.5     Sud
3              4          Andalucia        773                  50.7     Sud
4              5          Andalucia        277                  61.4     Sud
..           ...                ...        ...                   ...     ...
165          166           La Rioja        944                  89.4  Altres
166          167              Ceuta        208                  88.5  Altres
167          168            Melilla        652                  88.4  Altres
168          169           La Rioja        126                  54.8  Altres
169          170           La Rioja        517                  65.5  Altres

[170 rows x 5 columns]

### Ejercicio 8 - ~isin() isnot()
Crea una función llamada hospitales_no_catalunya(df) que:

- filtre los hospitales que NO estén en "Cataluña" ni "Madrid"
- entre esos hospitales, seleccione solo los que tengan más de 200 camas y retorne únicamente las columnas: hospital_id, comunidad_autonoma, num_camas, porcentaje_ocupacion

In [32]:
data = pd.read_csv("hospitales.csv", sep=";", encoding="latin-1")

def hospitales_no_catalunya(df):

    df_filtrado = df.loc[
        (~df["comunidad_autonoma"].isin(["Cataluña", "Madrid"])) &
        (df["num_camas"] > 200),
        ["hospital_id", "comunidad_autonoma", "num_camas", "porcentaje_ocupacion"]
    ]

    return df_filtrado

hospitales_no_catalunya(data)

     hospital_id comunidad_autonoma  num_camas  porcentaje_ocupacion
0              1          Andalucia        645                  96.8
1              2          Andalucia        575                  78.5
2              3          Andalucia        834                  81.5
3              4          Andalucia        773                  50.7
4              5          Andalucia        277                  61.4
..           ...                ...        ...                   ...
163          164         Pais Vasco        281                  51.7
165          166           La Rioja        944                  89.4
166          167              Ceuta        208                  88.5
167          168            Melilla        652                  88.4
169          170           La Rioja        517                  65.5

[125 rows x 4 columns]